# Generated by Django 2.0.3 on 2018-03-08 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50)),
                ('participant_age', models.PositiveIntegerField()),
                ('env_exposures', models.TextField()),
                ('gen_mutations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.ParticipantInfo')),
            ],
        ),
    ]
