# Generated by Django 2.0.3 on 2018-03-08 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantinfo',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
