# Generated by Django 2.0.3 on 2018-03-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participantinfo_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantinfo',
            name='participant_siblings',
            field=models.CharField(choices=[('Yes', 1), ('No', 0)], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='participantinfo',
            name='rev_status',
            field=models.CharField(choices=[('Not Reviewed', 0), ('Reviewed - Accepted', 1), ('Reviewed - Not Accepted', 2)], default='Not Reviewed', max_length=23),
        ),
    ]
