# Generated by Django 2.0.3 on 2018-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20180308_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantinfo',
            name='participant_siblings',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='participantinfo',
            name='rev_status',
            field=models.CharField(choices=[('Not Reviewed', 'Not Reviewed'), ('Reviewed - Accepted', 'Reviewed - Accepted'), ('Reviewed - Not Accepted', 'Reviewed - Not Accepted')], default='Not Reviewed', max_length=23),
        ),
    ]
