# Generated by Django 2.0.3 on 2018-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_auto_20180308_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantslist',
            name='participant',
        ),
        migrations.AlterField(
            model_name='participantinfo',
            name='participant_siblings',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.DeleteModel(
            name='ParticipantsList',
        ),
    ]
