# Generated by Django 2.0.3 on 2018-03-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_auto_20180310_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_status', models.CharField(choices=[('Not Reviewed', 'Not Reviewed'), ('Reviewed - Accepted', 'Reviewed - Accepted'), ('Reviewed - Not Accepted', 'Reviewed - Not Accepted')], default='Not Reviewed', max_length=23)),
            ],
        ),
    ]
