# Generated by Django 2.0.3 on 2018-03-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_reviewstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewstatus',
            name='rev_status',
            field=models.CharField(choices=[('Not Reviewed', 'Not Reviewed'), ('Reviewed - Accepted', 'Reviewed - Accepted'), ('Reviewed - Not Accepted', 'Reviewed - Not Accepted')], default='Reviewed - Not Accepted', max_length=23),
        ),
    ]
