# Generated by Django 2.0.3 on 2018-03-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_auto_20180311_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewStatus',
        ),
    ]
