# Generated by Django 2.0.3 on 2018-03-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_delete_reviewstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='participantinfo',
            name='participant_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
