# Generated by Django 2.0.3 on 2018-03-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20180312_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantinfo',
            name='rev_status',
            field=models.CharField(choices=[('Not Reviewed', 'NoReview'), ('Reviewed - Accepted', 'Accepted'), ('Reviewed - Not Accepted', 'NotAccepted')], default='Not Reviewed', max_length=23),
        ),
    ]
