# Generated by Django 2.0.3 on 2018-03-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_auto_20180312_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantinfo',
            old_name='env_exposures',
            new_name='environmental_exposures',
        ),
        migrations.RenameField(
            model_name='participantinfo',
            old_name='gen_mutations',
            new_name='genetic_mutations',
        ),
        migrations.RenameField(
            model_name='participantinfo',
            old_name='rev_status',
            new_name='review_status',
        ),
    ]
