# Generated by Django 2.0.3 on 2018-03-13 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0011_auto_20180313_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantinfo',
            name='participant_age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
